apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
  namespace: k8s-demo
spec:
  ingressClassName: traefik
  rules:
    - host: k8s-demo.blackjackzone.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80