apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-data
  namespace: k8s-demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: oci-bv
  resources:
    requests:
      storage: 50Gi